name: Test Github Action
on:
  push:
    branches: [ master, dev, qa, stage ]
  workflow_dispatch:
    inputs:
      phase:
        type: choice
        description: 'Phase'
        default: dev
        options:
          - dev
          - qa
          - stage
          - real

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Test Github
        env:
          PHASE: ${{ github.event.inputs.phase }}
          TARGET_BRANCH: ${{ github.ref_name }}
        run: |
          echo "phase: ${{ github.event.inputs.phase }}"
          echo "github.env: ${{ github.env }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          
          if [[ "$PHASE" == "" ]]; then
            if [[ "$TARGET_BRANCH" == "qa" ]]; then
              echo "register based on $TARGET_BRANCH"
            else
              echo "else: $TARGET_BRANCH"
            fi
          else
            echo "else $PHASE"
          fi 
