name: Test Github Script
on:
  pull_request:
    branches: [ master ]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            console.log(context)
            echo "${{steps.set-result.outputs.result}}"
            
            echo "context: "
            
            var request = {
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "pr 코멘트에 메시지가 넣어지는지 확인"
            }
            
            github.rest.issues.createComment(request)
